sequenceDiagram
    autonumber
    Game server->>Master server: heartbeat
    Master server->>Game server: getinfo
    Note left of Master server: A_ch4Lleng3
    Game server->>Master server: infoResponse
    Note right of Game server: A_ch4Lleng3
